### ISSUE TITLE
Add ability to authenticate external users under LAI

### ISSUE THREAD

**Issue by stevehannauu** [usnistgov/FederalProfile-8259A#206]
IoT systems frequently need to communicate with external systems (e.g., cloud). When doing so, authentication is essential. Therefore, I recommend adding a new bullet to the Logical Access to Interfaces section of the technical requirements:

> Ability to authenticate external users and systems, and to revoke their access

**Comment by kevingbrady** [comment]
"Thank you for your comments. They've been reviewed and have been useful to our technical team. You will soon see the updated versions of these catalogs on the new GitHub page: IoT Device Cybersecurity Requirements Catalog."
