### ISSUE TITLE
Add ability to continue operation when external networks are unavailable

### ISSUE THREAD

**Issue by stevehannauu** [usnistgov/FederalProfile-8259A#207]
The special power of IoT systems often comes from their ability to communicate with or make use of external systems. However, they should not become unusable if those external systems are unavailable (as can happen for many reasons). For this reason, the following bullet should be added to the Device Security section of the technical requirements under Secure Device Operation:

> Ability to continue operation when external networks are unavailable.

**Comment by kevingbrady** [comment]
"Thank you for your comments. They've been reviewed and have been useful to our technical team. You will soon see the updated versions of these catalogs on the new GitHub page: IoT Device Cybersecurity Requirements Catalog."
