### ISSUE TITLE
NIST should reiterate its commitment to a voluntary and flexible approach to IoT security and roundly reject calls for rigid regulation of IoT.

### ISSUE THREAD

**Issue by MelanieTiano-CTIA** [usnistgov/FederalProfile-8259A#211]
**Organization Name:**  CTIA
**Organization Type:**  Association that represents the U.S. wireless communications industry and the companies throughout the mobile ecosystem that enable Americans to lead a 21st century connected life.
**Document (Technical capabilities, Nontechnical capabilities):**  Both technical and nontechnical capabilities
**Feedback:**   NIST should double down on its commitment to a flexible, non-regulatory approach to cybersecurity.  Calls for prescriptive mandates would ultimately harm—not help—the effort to improve IoT device security in the Federal government and beyond.  See attachment for CTIA’s full submission; Section V provides the full rationale for this feedback.
**Organization:** Industry

[CTIA Comments re NIST Federal Profile - 08-07-2020.pdf](https://github.com/usnistgov/FederalProfile-8259A/files/5044016/CTIA.Comments.re.NIST.Federal.Profile.-.08-07-2020.pdf)

**Comment by kevingbrady** [comment]
"Thank you for your comments. They've been reviewed and have been useful to our technical team. You will soon see the updated versions of these catalogs on the new GitHub page: IoT Device Cybersecurity Requirements Catalog."
