### ISSUE TITLE
Missing Glossary section

### ISSUE THREAD

**Issue by jlepp-BLACKBERRY** [usnistgov/FederalProfile-8259A#221]
The terms used in the federal profile documents have specific meaning. We think it would improve device manufactures understanding if the both documents have glossary section. The glossary would also help with an issue that some terminologies, e.g. “organizationally-defined condition”, “organizationally-defined account” are referred to only by the technical profile but not the non-technical profile. We think that those terminologies should be also in the non-technical profile.

**Comment by kevingbrady** [comment]
"Thank you for your comments. They've been reviewed and have been useful to our technical team. You will soon see the updated versions of these catalogs on the new GitHub page: IoT Device Cybersecurity Requirements Catalog."
