### ISSUE TITLE
Comment on the list of cryptographic primitive abilities in _Technical/protection.md.

### ISSUE THREAD

**Issue by jlepp-BLACKBERRY** [usnistgov/FederalProfile-8259A#222]
Can you clarify if the listed abilities (cryptographic primitives) are to be implemented in-line with crypto related FIPS standards? We would recommend that the algorithms used be a subset of FIPS 140.

**Comment by kevingbrady** [comment]
"Thank you for your comments. They've been reviewed and have been useful to our technical team. You will soon see the updated versions of these catalogs on the new GitHub page: IoT Device Cybersecurity Requirements Catalog."
