### ISSUE TITLE
Response to question 6

### ISSUE THREAD

**Issue by jlepp-BLACKBERRY** [usnistgov/FederalProfile-8259A#223]
6. Do you find it useful to have the technical capabilities catalog separate from the non-technical capabilities? Why or why not? 

No - while reviewing the non-technical document we found the separation between the two documents to be an added challenge. The non-technical document was missing important contextual information we found non-technical guidance was missing key areas, when in fact they were covered under the technical document.
 
Having that important contextual information together in a single document would ease comprehension, and also reduces the risk of a manufacturer missing key guidance by only reading one document and not the other. If kept separate, cross references between technical and non-technical capability elements would help. For example, in the role support and management section, it would increase understanding of the readers if which non-tech capabilities are aligned with tech capabilities.

**Comment by kevingbrady** [comment]
"Thank you for your comments. They've been reviewed and have been useful to our technical team. You will soon see the updated versions of these catalogs on the new GitHub page: IoT Device Cybersecurity Requirements Catalog."
