### ISSUE TITLE
Denial of Service protection

### ISSUE THREAD

**Issue by jlepp-BLACKBERRY** [usnistgov/FederalProfile-8259A#236]
The profile contains only a single line about denial of service (DoS) protection and it is specific to the context of compressing log files to prevent running out of space for logs. Per SP 800-53 SC-5 we’d suggest to add text to “restrict the ability to attack other systems” as a more general denial of service protection related ability.

**Comment by kevingbrady** [comment]
"Thank you for your comments. They've been reviewed and have been useful to our technical team. You will soon see the updated versions of these catalogs on the new GitHub page: IoT Device Cybersecurity Requirements Catalog."
